// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
public final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum HybridNavPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// A destination path, e.g. `/project/42`.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct NavRoute: Hashable, CustomStringConvertible {
  public var path: String

  public init(path: String) { self.path = path }


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NavRoute? {
    let path = pigeonVar_list[0] as! String

    return NavRoute(
      path: path
    )
  }
  func toList() -> [Any?] {
    return [
      path
    ]
  }
  public static func == (lhs: NavRoute, rhs: NavRoute) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return HybridNavPigeonInternal.deepEquals(lhs.path, rhs.path)
  }

  public func hash(into hasher: inout Hasher) {
    hasher.combine("NavRoute")
    HybridNavPigeonInternal.deepHash(value: path, hasher: &hasher)
  }

  public var description: String {
    return "NavRoute(path: \(String(describing: path)))"
  }
}

private class HybridNavPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return NavRoute.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class HybridNavPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NavRoute {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class HybridNavPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return HybridNavPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return HybridNavPigeonCodecWriter(data: data)
  }
}

class HybridNavPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = HybridNavPigeonCodec(readerWriter: HybridNavPigeonCodecReaderWriter())
}

/// Flutter → native. Swift/Kotlin implement it; Dart calls it.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
public protocol ToNative {
  /// Push a native screen for [route].
  func pushNativeRoute(route: NavRoute) throws
  /// We're leaving Flutter: destroy the Flutter view and reveal the native
  /// screen underneath.
  func returnToNative() throws
  /// Clear the native stack back to its root.
  func popToRoot() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
public class ToNativeSetup {
  static var codec: FlutterStandardMessageCodec { HybridNavPigeonCodec.shared }
  /// Sets up an instance of `ToNative` to handle messages through the `binaryMessenger`.
  public static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ToNative?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Push a native screen for [route].
    let pushNativeRouteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hybrid_router.ToNative.pushNativeRoute\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pushNativeRouteChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let routeArg = args[0] as! NavRoute
        do {
          try api.pushNativeRoute(route: routeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pushNativeRouteChannel.setMessageHandler(nil)
    }
    /// We're leaving Flutter: destroy the Flutter view and reveal the native
    /// screen underneath.
    let returnToNativeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hybrid_router.ToNative.returnToNative\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      returnToNativeChannel.setMessageHandler { _, reply in
        do {
          try api.returnToNative()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      returnToNativeChannel.setMessageHandler(nil)
    }
    /// Clear the native stack back to its root.
    let popToRootChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hybrid_router.ToNative.popToRoot\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      popToRootChannel.setMessageHandler { _, reply in
        do {
          try api.popToRoot()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      popToRootChannel.setMessageHandler(nil)
    }
  }
}

/// Native → Flutter. Dart implements it; Swift/Kotlin call it.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
public protocol ToFlutterProtocol {
  /// Show a Flutter page that native opened.
  func pushFlutterRoute(route routeArg: NavRoute, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Native asks first on every back gesture. Returns whether Flutter
  /// consumed it.
  func handleBack(completion: @escaping (Result<Bool, PigeonError>) -> Void)
}
public class ToFlutter: ToFlutterProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  public init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: HybridNavPigeonCodec {
    return HybridNavPigeonCodec.shared
  }
  /// Show a Flutter page that native opened.
  public func pushFlutterRoute(route routeArg: NavRoute, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.hybrid_router.ToFlutter.pushFlutterRoute\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([routeArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Native asks first on every back gesture. Returns whether Flutter
  /// consumed it.
  public func handleBack(completion: @escaping (Result<Bool, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.hybrid_router.ToFlutter.handleBack\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(.failure(PigeonError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! Bool
        completion(.success(result))
      }
    }
  }
}
